apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: xgboost-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: xgboost-operator
      app.kubernetes.io/instance: xgboost-operator
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: xgboostjob
      app.kubernetes.io/part-of: kubeflow
  componentKinds:
  - group: core
    kind: Service
  - group: extensions/v1beta1
    kind: Deployment
  - group: core
    kind: ServiceAccount
  - group: xgboostjob.kubeflow.org
    kind: XGBoostJob
  descriptor: 
    type: xgboostjob
    version: v1alpha1
    description: XGBoost is an optimized distributed gradient boosting library designed to be highly efficient, flexible and portable
    maintainers:
    - name: Yuan Tang
      email: terrytangyuan@gmail.com
    - name: Hemantha kumara
      email: mshemantha@gmail.com
    owners:
    - name: Yuan Tang
      email: terrytangyuan@gmail.com
    keywords:
     - xgboost
    links:
    - description: About
      url: "https://xgboost.ai/about"
  addOwnerRef: true
