---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: evaluator
  namespace: tfra-dev
spec:
  serviceName: evaluator-svc
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: evaluator
  template:
    metadata:
      name: evaluator
      labels:
        k8s-app: evaluator
    spec:
      nodeSelector:
        train : "true"
        cpu: "true"
      containers:
      - name: app
        image: mirrors.tencent.com/uthermai/tmeps:trainning
        imagePullPolicy: Always
        env:
        - name: "whoami"
          value: "evaluator"
        resources:
          limits:
            cpu: 4000m
            memory: 8000Mi
          requests:
            cpu: 4000m
            memory: 8000Mi

---
apiVersion: v1
kind: Service
metadata:
  name: evaluator-svc
  namespace: tfra-dev
  labels:
    k8s-app: evaluator
spec:
  ports:
    - port: 2223
  clusterIP: "None"
  selector:
    k8s-app: evaluator
