resources:
- ps.yaml
- worker.yaml
- chief.yaml
- evaluator.yaml
- server.yaml
- saver.yaml

# 命名空间
namespace: tfra-dev

# pod名字前缀，可以区分不同项目
namePrefix: test-model-

commonLabels:
  trainning-model: test-model

# 集群规模
replicas:
- name: ps
  count: 2
- name: worker
  count: 4
- name: chief
  count: 1
- name: evaluator
  count: 1
- name: server
  count: 1
- name: saver
  count: 1

patches:
# 挂载conf文件、分布式存储目录
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
        - name: serving-models-conf
          mountPath: /tmp/conf/serving-models-conf
        - name: redis-backend-conf
          mountPath: /tmp/conf/redis-backend-conf
        - name: uthermai-data
          mountPath: /mnt/uthermai
      - op: add
        path: /spec/template/spec/volumes
        value:
        - name: serving-models-conf
          configMap:
            name: serving-models-conf
            defaultMode: 493
        - name: redis-backend-conf
          configMap:
            name: redis-backend-conf
            defaultMode: 493
        - name: uthermai-data
          hostPath:
            path: /data/k8s/kubeflow/pipeline/workspace/uthermai
    target:
      version: v1
      kind: StatefulSet

# 模型、checkpoint、数据目录的路径
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env"
        value:
        - name: "model_serving_config_path"
          value: "/tmp/conf/serving-models-conf/serving_models.conf"
        - name: "model_tfra_redis_config_path"
          value: "/tmp/conf/redis-backend-conf/redis_backend.conf"
        - name: "checkpoint_path"
          value: "/mnt/uthermai/tmp/checkpoint"
        - name: "model_path"
          value: "/mnt/uthermai/tmp/saved_model"
        - name: "data_path"
          value: "/mnt/uthermai/tmp"
    target:
      version: v1
      kind: StatefulSet

# 集群结构
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: "ps_cluster_config"
          value: '{"cluster": {"evaluator": ["test-model-evaluator-0.test-model-evaluator-svc.tfra-dev.svc.cluster.local:2223"], "worker": ["test-model-worker-0.test-model-worker-svc.tfra-dev.svc.cluster.local:2223", "test-model-worker-1.test-model-worker-svc.tfra-dev.svc.cluster.local:2223", "test-model-worker-2.test-model-worker-svc.tfra-dev.svc.cluster.local:2223", "test-model-worker-3.test-model-worker-svc.tfra-dev.svc.cluster.local:2223"], "ps": ["test-model-ps-0.test-model-ps-svc.tfra-dev.svc.cluster.local:2223"], "chief": ["test-model-chief-0.test-model-chief-svc.tfra-dev.svc.cluster.local:2223"]}}'
    target:
      version: v1
      kind: StatefulSet
      name: ps|worker|chief|evaluator

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: "ps_cluster_config"
          value: '{"cluster": {"evaluator": ["test-model-evaluator-0.test-model-evaluator-svc.tfra-dev.svc.cluster.local:2223"], "worker": ["test-model-worker-0.test-model-worker-svc.tfra-dev.svc.cluster.local:2223", "test-model-worker-1.test-model-worker-svc.tfra-dev.svc.cluster.local:2223", "test-model-worker-2.test-model-worker-svc.tfra-dev.svc.cluster.local:2223", "test-model-worker-3.test-model-worker-svc.tfra-dev.svc.cluster.local:2223"], "ps": ["test-model-ps-0.test-model-ps-svc.tfra-dev.svc.cluster.local:2223"], "chief": ["test-model-chief-0.test-model-chief-svc.tfra-dev.svc.cluster.local:2223"], "saver":["test-model-saver-0.test-model-saver-svc.tfra-dev.svc.cluster.local:2223"]}}'
    target:
      version: v1
      kind: StatefulSet
      name: saver
