---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: worker
  namespace: tfra-dev
spec:
  serviceName: worker-svc
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: worker
  template:
    metadata:
      name: worker
      labels:
        k8s-app: worker
    spec:
      nodeSelector:
        train : "true"
        cpu: "true"
      containers:
      - name: app
        image: ai.tencentmusic.com/tme-public/tmeps:trainning
        imagePullPolicy: Always
        env:
        - name: "whoami"
          value: "worker"
        resources:
          limits:
            cpu: 2000m
            memory: 4000Mi
          requests:
            cpu: 2000m
            memory: 4000Mi

---
apiVersion: v1
kind: Service
metadata:
  name: worker-svc
  namespace: tfra-dev
  labels:
    k8s-app: worker
spec:
  ports:
    - port: 2223
  clusterIP: "None"
  selector:
    k8s-app: worker
