apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: minio
spec:
  addOwnerRef: true
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  descriptor:
    description: ''
    keywords:
    - minio
    - kubeflow
    links:
    - description: About
      url: ''
    maintainers: []
    owners: []
    type: minio
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/component: minio
      app.kubernetes.io/name: minio
