apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-auth-login
spec:
  selector:
    matchLabels:
      app: basic-auth-login
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: basic-auth-login
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubeflow
                    operator: In
                    values:
                      - "true"
      containers:
      - name: app
        image: gcr.io/kubeflow-images-public/kflogin-ui:v0.5.0
        ports:
        - containerPort: 5000
