---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeflow-mysql-pv
  labels:
    kubeflow-pvname: kubeflow-mysql-pv
spec:
  capacity:       
    storage: 20Gi
  accessModes:   
    - ReadWriteOnce   
  hostPath:
    path: /data/k8s/kubeflow/mysql  
  persistentVolumeReclaimPolicy: Retain



