kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-minio
  namespace: infra
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
