# encoding: utf-8
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-dashboard
  namespace: infra
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeflow-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["pods","pods/log","services","endpoints","configmaps","nodes","deployments","mpijobs","tfjobs","pytorchjobs","frameworks"]
  verbs: ["create", "delete", "deletecollection", "patch", "update", "get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["create", "delete", "deletecollection", "patch", "update", "get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeflow-dashboard
subjects:
- kind: ServiceAccount
  name: kubeflow-dashboard
  namespace: infra
roleRef:
  kind: ClusterRole
  name: kubeflow-clusterrole
  apiGroup: rbac.authorization.k8s.io



