apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-db-manager
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubeflow
                    operator: In
                    values:
                      - "true"
      containers:
        - name: katib-db-manager
          env:
            - name: DB_NAME
              value: mysql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: katib-mysql-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: katib-mysql-secrets
                  key: DB_PASSWORD
            - name: KATIB_MYSQL_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: katib-mysql-secrets
                  key: KATIB_MYSQL_DB_DATABASE
            - name: KATIB_MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: katib-mysql-secrets
                  key: KATIB_MYSQL_DB_HOST
            - name: KATIB_MYSQL_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: katib-mysql-secrets
                  key: KATIB_MYSQL_DB_PORT
