apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
commonLabels:
  kustomize.component: spartakus
images:
- name: gcr.io/google_containers/spartakus-amd64
  newName: gcr.io/google_containers/spartakus-amd64
  newTag: v1.1.0
configMapGenerator:
- name: spartakus-config
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
