# This is a custom spawnerUiConfig.
#
# It looks like the entire file is replaced; so the user would need to supply a complete
# spawner config.
spawnerFormDefaults:
  image:
    # The container Image for the user's Jupyter Notebook
    # If readonly, this value must be a member of the list below
    value: alicerepo/tensorflow-1.14.0-notebook-cpu:v-base-ef41372-1177829795472347138
    # The list of available standard container Images
    options:
      - alicerepo/tensorflow-1.15.2-notebook-cpu:1.0.0
      - alicerepo/tensorflow-1.15.2-notebook-gpu:1.0.0
      - alicerepo//tensorflow-2.1.0-notebook-cpu:1.0.0
      - alicerepo//tensorflow-2.1.0-notebook-gpu:1.0.0