apiVersion: v1
data:
  redis_backend.conf: |-
    {
      "redis_connection_mode": 0,
      "redis_master_name": "master",
      "redis_host_ip": [
        "redis.tfra-dev"
      ],
      "redis_host_port": [
        6379
      ],
      "redis_user": "default",
      "redis_password": "admin",
      "redis_db": 0,
      "redis_read_access_slave": true,
      "redis_connect_keep_alive": true,
      "redis_connect_timeout": 2000,
      "redis_socket_timeout": 2000,
      "redis_conn_pool_size": 200,
      "redis_wait_timeout": 100000000,
      "redis_connection_lifetime": 100,
      "redis_sentinel_connect_timeout": 1000,
      "redis_sentinel_socket_timeout": 1000,
      "storage_slice": 3,
      "keys_sending_size": 1024,
      "using_md5_prefix_name": false,
      "model_tag_import": "test-model",
      "redis_hash_tags_import": [
        "{1234}",
        "{1235}",
        "{1236}"
      ],
      "model_tag_runtime": "test-model",
      "redis_hash_tags_runtime": [
        "{1234}",
        "{1235}",
        "{1236}"
      ],
      "expire_model_tag_in_seconds": 604800,
      "table_store_mode": 2,
      "model_lib_abs_dir": "/tmp/"
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: redis-backend-conf
  namespace: tfra-dev
