apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modeldb
  name: modeldb-webapp
spec:
  selector:
    matchLabels:
      app: modeldb
      tier: webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeldb
        tier: webapp
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubeflow
                    operator: In
                    values:
                      - "true"
      containers:
      - image: vertaaiofficial/modeldb-frontend:kubeflow
        imagePullPolicy: IfNotPresent
        name: modeldb-webapp
        ports:
        - containerPort: 3000
