version: '3'
services:
  redis:
    image: bitnami/redis:4.0.14
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: admin
    ports:
      - "6379:6379"

#  mysql:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#
  frontend:
    image: ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard-frontend:2022.09.01
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ../../myapp/static/appbuilder/frontend:/data/web/frontend
      - ../../install/docker/dockerFrontend/nginx.conf:/etc/nginx/nginx.conf
      - ../../install/docker/dockerFrontend/nginx.80.conf:/etc/nginx/conf.d/default.conf

  myapp:
    image:  ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard:2022.09.01
    restart: always
    command: ['bash','-c','sleep 10000000 && /entrypoint.sh']
    environment:
      STAGE: 'dev'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: admin
      MYSQL_SERVICE: 'mysql+pymysql://root:admin@mysql:3306/kubeflow?charset=utf8'
      ENVIRONMENT: DEV
      GPU_TYPE: NVIDIA
#    ports:
#      - "8080:80"
    depends_on:
      - redis
      - mysql
    volumes:
      - ../../myapp/static/appbuilder/frontend:/data/web/frontend
      - ../../myapp/:/home/myapp/myapp/
      - ./file:/pvc
      - ./entrypoint.sh:/entrypoint.sh
      - ./config.py:/home/myapp/myapp/config.py
      - ./kubeconfig:/home/myapp/kubeconfig


#  beat:
#    image: ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard:2022.09.01
#    restart: "no"
#    command: ["bash","-c","celery beat --app=myapp.tasks.celery_app:celery_app --loglevel=info"]
#    shm_size: '100gb'
#    environment:
#      REDIS_HOST: 'redis'
#      REDIS_PORT: '6379'
#      REDIS_PASSWORD: admin
#      MYSQL_SERVICE: 'mysql+pymysql://root:admin@host.docker.internal:3306/kubeflow?charset=utf8'
#      ENVIRONMENT: DEV
#    depends_on:
#      - redis
#    volumes:
#      - ../../myapp/:/home/myapp/myapp/
#      - ./file:/pvc
#      - ./entrypoint.sh:/entrypoint.sh
#      - ./config.py:/home/myapp/myapp/config.py
#      - ./kubeconfig:/home/myapp/kubeconfig


#

#  worker:
#    image: ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard:2022.09.01
#    restart: unless-stopped
#    command: ["bash","-c","celery worker --app=myapp.tasks.celery_app:celery_app --loglevel=info --pool=prefork -Ofair -c 40"]
#    environment:
#      REDIS_HOST: 'redis'
#      REDIS_PORT: '6379'
#      REDIS_PASSWORD: admin
#      MYSQL_SERVICE: 'mysql+pymysql://root:admin@host.docker.internal:3306/kubeflow?charset=utf8'
#      ENVIRONMENT: DEV
#    depends_on:
#      - redis
#    volumes:
#      - ../../myapp/:/home/myapp/myapp/
#      - ./file:/pvc
#      - ./entrypoint.sh:/entrypoint.sh
#      - ./config.py:/home/myapp/myapp/config.py
#      - ./kubeconfig:/home/myapp/kubeconfig
#


