version: '3'
services:
  redis:
    image: bitnami/redis:4.0.14
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: admin
    ports:
      - "6379:6379"

#  mysql:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: kubeflow
#      TZ: Asia/Shanghai
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./data/mysql:/var/lib/mysql

  frontend:
    image: ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard-frontend:2023.01.01
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ../../myapp/static/appbuilder/frontend:/data/web/frontend
      - ../../install/docker/dockerFrontend/nginx.conf:/etc/nginx/nginx.conf
      - ../../install/docker/dockerFrontend/nginx.80.conf:/etc/nginx/conf.d/default.conf

  myapp:
    image:  ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard:2023.01.01
    restart: unless-stopped
    command: ['bash','-c','sleep 1000000000 && /entrypoint.sh']
    environment:
      STAGE: 'dev'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: admin
      MYSQL_SERVICE: 'mysql+pymysql://root:admin@host.docker.internal:3306/kubeflow1?charset=utf8'
      ENVIRONMENT: DEV
      GPU_TYPE: NVIDIA
#    ports:
#      - "8080:80"
    depends_on:
      - redis
    volumes:
      - ../../myapp/static/appbuilder/frontend:/data/web/frontend
      - ../../myapp/:/home/myapp/myapp/
      - ../../aihub/:/cube-studio/aihub/
      - ./file:/pvc
      - ./entrypoint.sh:/entrypoint.sh
      - ./config.py:/home/myapp/myapp/config.py
      - ./kubeconfig:/home/myapp/kubeconfig


#  beat:
#    image: ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard:2023.01.01
#    restart: "no"
#    command: ["bash","-c","celery --app=myapp.tasks.celery_app:celery_app beat --loglevel=info"]
#    shm_size: '100gb'
#    environment:
#      REDIS_HOST: 'redis'
#      REDIS_PORT: '6379'
#      REDIS_PASSWORD: admin
#      MYSQL_SERVICE: 'mysql+pymysql://root:admin@host.docker.internal:3306/kubeflow?charset=utf8'
#      ENVIRONMENT: DEV
#    depends_on:
#      - redis
#    volumes:
#      - ../../myapp/:/home/myapp/myapp/
#      - ./file:/pvc
#      - ./entrypoint.sh:/entrypoint.sh
#      - ./config.py:/home/myapp/myapp/config.py
#      - ./kubeconfig:/home/myapp/kubeconfig
##
#
##
#
#  worker:
#    image: ccr.ccs.tencentyun.com/cube-studio/kubeflow-dashboard:2023.01.01
#    restart: unless-stopped
#    # 默认的prefork池针对长时间的任务支持不是很好，如果任务运行时间有数分钟/小时，建议启用 Celery 的 -Ofair 命令参数
#    command: ["bash","-c","celery --app=myapp.tasks.celery_app:celery_app worker --loglevel=info --pool=prefork -Ofair -c 2 -n worker@%h"]
#    environment:
#      REDIS_HOST: 'redis'
#      REDIS_PORT: '6379'
#      REDIS_PASSWORD: admin
#      MYSQL_SERVICE: 'mysql+pymysql://root:admin@host.docker.internal:3306/kubeflow?charset=utf8'
#      ENVIRONMENT: DEV
#    depends_on:
#      - redis
#    volumes:
#      - ../../myapp/:/home/myapp/myapp/
#      - ./file:/pvc
#      - ./entrypoint.sh:/entrypoint.sh
#      - ./config.py:/home/myapp/myapp/config.py
#      - ./kubeconfig:/home/myapp/kubeconfig
#


