apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- gateway.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-role.yaml
- service-role-binding.yaml
- config-map.yaml
- deployment.yaml
- secret.yaml
- service-account.yaml
- service.yaml
- image.yaml
- hpa.yaml
- webhook-configuration.yaml
commonLabels:
  kustomize.component: knative
images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newTag: ffa3d72ee6c2eeb2357999248191a643405288061b7080381f22875cb703e929
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newTag: f89fd23889c3e0ca3d8e42c9b189dc2f93aa5b3a91c64e8aab75e952a210eeb3
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newTag: 7e6df0fda229a13219bbc90ff72a10434a0c64cd7fe13dc534b914247d1087f4
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newTag: b86ac8ecc6b2688a0e0b9cb68298220a752125d0a048b8edf2cf42403224393c
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newTag: 75c7918ca887622e7242ec1965f87036db1dc462464810b72735a8e64111f6f7
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newTag: e6b142c0f82e0e0b8cb670c11eb4eef6ded827f98761bbf4bea7bdb777b80092
