apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../katib-controller/base/katib-db-manager-deployment.yaml
  - ../../katib-controller/base/katib-db-manager-service.yaml
images:
  - name: docker.io/kubeflowkatib/katib-db-manager
    newTag: v1beta1-a96ff59
    newName: docker.io/kubeflowkatib/katib-db-manager
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-controller
