apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set
spec:
  serviceName: service
  selector:
    matchLabels:
      app: application-controller
  template:
    metadata:
      labels:
        app: application-controller
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubeflow
                    operator: In
                    values:
                      - "true"
      containers:
      - name: manager
        command:
        - /root/manager
        image: gcr.io/kubeflow-images-public/kubernetes-sigs/application
        imagePullPolicy: IfNotPresent
        env:
        # TODO(https://github.com/kubeflow/manifests/issues/1043)
        # Do we really need this?
        - name: project
          value: $(project)
      serviceAccountName: service-account
  volumeClaimTemplates: []
