apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
namespace: kubeflow
namePrefix: xgboost-operator-
configMapGenerator:
- envs:
  - params.env
  name: xgboost-operator-config
images:
- name: gcr.io/kubeflow-images-public/xgboost-operator
  newName: gcr.io/kubeflow-images-public/xgboost-operator
  newTag: vmaster-g56c2c075
